### ISSUE TITLE
Fonctionnement avec Kodi (XBMC v14)

### ISSUE THREAD

**Issue by inrepublica** [jdesgats/plugin.video.jeuxvideo.com#1]
Une intégration de l'addon sur le repo pour Kodi est-elle envisagée?

**Comment by jdesgats** [comment]
Il faut que je teste sur la v14. Mais à priori ça ne devrait pas être un problème :)

Pour l'instant l'addon n'est dispo que sur la v13: http://addons.xbmc.org/show/plugin.video.jeuxvideo.com/

**Comment by inrepublica** [comment]
Je viens de tester il manque des dépendances. A priori python ce n'est pas un problème, par contre xbmcswift ne semble pas dispo dans le repo...

**Comment by inrepublica** [comment]
Je viens de remarquer que le plugin est acceptible depuis le dépot en v14, c'est super! Merci à toi.
