### ISSUE TITLE
jv.com api down

### ISSUE THREAD

**Issue by Celedhrim** [jdesgats/plugin.video.jeuxvideo.com#3]
L'api est maintenant en 404.

Maintient tu encore cette addon , ou je me lance dans quelque chose ? :)

je pensais utiliser les xml de podcast du coup !

**Comment by jdesgats** [comment]
Salut,

Toujours au poste mais pas mal pris ces derniers temps :) J'avais remarqué le plugin marchait plus trop depuis quelques jours, sans avoir le temps de debugger... Je vais essayer de bricoler un truc avec l'API RSS.

**Comment by Celedhrim** [comment]
ok merci a toi ! :)

**Comment by jdesgats** [comment]
J'ai changé les appels API par les flux RSS et un peu de magie pour avoir les thumbnails et les différentes définitions de vidéos. J'ai pas vu de problème particulier. Est-ce que tu peux me confirmer que ça marche de ton coté?

**Comment by Celedhrim** [comment]
Ça marche impec ! 

Merci , rapide et efficace :)

**Comment by jdesgats** [comment]
Merged upstream: https://github.com/xbmc/repo-plugins/pull/404
